// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const numberInputApi: ComponentApiDoc = {
  name: "NumberInput",
  description: "Numeric input with increment and decrement buttons, composed inside `InputGroup`. Clamps the value between `min` and `max`; the corresponding button disables once a limit is reached. `step` sets the amount added or subtracted per button press.",
  props: [
    {
      name: "value",
      kind: "model",
      required: false,
      type: "number | null",
      defaultValue: "null",
      description: "Current numeric value, or `null` when empty. Two-way bindable via `[(value)]`; also works with `formControlName`/`ngModel`.",
    },
    {
      name: "min",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Minimum allowed value — the decrement button disables and blur clamps the value once reached.",
    },
    {
      name: "max",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Maximum allowed value — the increment button disables and blur clamps the value once reached.",
    },
    {
      name: "step",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "1",
      description: "Amount added or subtracted per +/- button press.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the input and both stepper buttons.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Native placeholder text shown when the value is empty.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static label text; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static helper/caption text below the input; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "state",
      kind: "input",
      required: false,
      type: "NumberInputState",
      defaultValue: "null",
      description: "Validation state, passed through to the underlying `InputGroup` border color.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Overrides the auto-generated element id (used to associate the label and caption).",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the input group.",
    },
  ],
};
