// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const numberInputApi: ComponentApiDoc = {
  name: "NumberInput",
  description: "Real `<input type=\"number\">` (native numeric keyboard on mobile, mouse-wheel and arrow-key increment for free) flanked by visible +/- stepper buttons that call the same clamp/step logic, composed inside `InputGroup` so the three pieces read as one bordered control. Reuses `Input`'s *conventions* (id-generation counter + `id` override, label/caption `UiTemplateDirective` slots, the same input text/border/disabled classes) rather than nesting `Input` itself: `Input`'s border/focus styling lives directly on its own inner `<input>` with no seam exposed to strip it for nesting inside a group without reaching into its internals. Own template + `InputGroup` composition avoids that. Buttons are real `<button type=\"button\">`s with `aria-label`s (they're icon-only), disabled individually once the value is clamped against `min`/`max`.",
  props: [
    {
      name: "value",
      kind: "model",
      required: false,
      type: "number | null",
      defaultValue: "null",
      description: "Current numeric value, or `null` when empty. Two-way bindable via `[(value)]`; also works with `formControlName`/`ngModel`.",
    },
    {
      name: "min",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Minimum allowed value — the decrement button disables and blur clamps the value once reached.",
    },
    {
      name: "max",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Maximum allowed value — the increment button disables and blur clamps the value once reached.",
    },
    {
      name: "step",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "1",
      description: "Amount added or subtracted per +/- button press.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the input and both stepper buttons.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Native placeholder text shown when the value is empty.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static label text; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static helper/caption text below the input; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "state",
      kind: "input",
      required: false,
      type: "NumberInputState",
      defaultValue: "null",
      description: "Validation state, passed through to the underlying `InputGroup` border color.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Overrides the auto-generated element id (used to associate the label and caption).",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the input group.",
    },
  ],
};
