// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const avatarApi: ComponentApiDoc = {
  name: "Avatar",
  description: "User or entity avatar with automatic fallback between an image, initials and an icon. When `src` is set the image is shown first, and falls back to `initials` (then `icon`) automatically if it fails to load. `alt` is the accessible name in every case: it is used as the `<img alt>` when an image renders, and as `aria-label` on the container otherwise.",
  props: [
    {
      name: "src",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Image URL, tried first. Falls back to `initials` (then `icon`) if unset or the image fails to load.",
    },
    {
      name: "alt",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Accessible name, used as `<img alt>` or `aria-label` depending on which tier renders (see class doc).",
    },
    {
      name: "initials",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Fallback text (e.g. initials) shown when there's no image; takes priority over `icon`.",
    },
    {
      name: "icon",
      kind: "input",
      required: false,
      type: "LucideIconInput | undefined",
      defaultValue: "undefined",
      description: "Fallback icon shown when there's no image and no `initials`. Defaults to a generic user icon.",
    },
    {
      name: "size",
      kind: "input",
      required: false,
      type: "AvatarSize",
      defaultValue: "'md'",
      description: "Overall size of the avatar and its fallback icon.",
    },
    {
      name: "shape",
      kind: "input",
      required: false,
      type: "AvatarShape",
      defaultValue: "'circle'",
      description: "Container shape.",
    },
    {
      name: "variant",
      kind: "input",
      required: false,
      type: "AvatarVariant",
      defaultValue: "'neutral'",
      description: "Background/text color used for the initials or icon fallback; ignored while an image is showing.",
    },
    {
      name: "status",
      kind: "input",
      required: false,
      type: "AvatarStatus",
      defaultValue: "'none'",
      description: "Presence indicator dot rendered in the bottom-right corner; `'none'` hides it.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the root element.",
    },
  ],
};
