// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const alertDialogApi: ComponentApiDoc = {
  name: "AlertDialog",
  description: "Confirmation dialog for actions that need an explicit confirm or cancel, such as deleting a record. Use it instead of `Modal` when the content is a `heading`, a `message` and two actions, rather than arbitrary projected content. Renders with `role=\"alertdialog\"` and exposes `message` through `aria-describedby` so assistive technology reads it together with the heading. Clicking the backdrop does not dismiss the dialog by default; Escape and the Cancel button both emit `cancelled`.",
  props: [
    {
      name: "open",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Controls dialog visibility, same as `Modal`'s `open` — the caller owns this and reacts to `confirmed`/`cancelled`.",
    },
    {
      name: "heading",
      kind: "input",
      required: true,
      type: "string",
      defaultValue: "",
      description: "Dialog title, rendered in the header and read first by assistive tech.",
    },
    {
      name: "message",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Body text describing the consequence of the action; wired to the panel's `aria-describedby`.",
    },
    {
      name: "confirmLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'Confirm'",
      description: "Label for the confirm button.",
    },
    {
      name: "cancelLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'Cancel'",
      description: "Label for the cancel button.",
    },
    {
      name: "variant",
      kind: "input",
      required: false,
      type: "AlertDialogVariant",
      defaultValue: "'default'",
      description: "`'danger'` styles the confirm button destructively, for irreversible actions like deletion.",
    },
    {
      name: "closeOnBackdrop",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Whether clicking the backdrop cancels the dialog. Defaults to `false`, unlike `Modal`.",
    },
    {
      name: "showCloseButton",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Shows an `X` close button in the header; clicking it cancels, same as Escape.",
    },
    {
      name: "loading",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the cancel button and shows a loading state on the confirm button while an async confirm is in flight.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the underlying `Modal` panel.",
    },
    {
      name: "confirmed",
      kind: "output",
      required: false,
      type: "void",
      defaultValue: "",
      description: "Fires when the confirm button is clicked.",
    },
    {
      name: "cancelled",
      kind: "output",
      required: false,
      type: "void",
      defaultValue: "",
      description: "Fires when the cancel button is clicked, the backdrop is clicked (if `closeOnBackdrop`), the close button is clicked, or Escape is pressed.",
    },
  ],
};
