// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const tooltipApi: ComponentApiDoc = {
  name: "Tooltip",
  description: "Floating tooltip panel used internally by the `uiTooltip` directive, which creates and positions instances of it on demand. Not meant to be used directly in a template; apply `uiTooltip` to an element instead.",
  props: [
    {
      name: "text",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Plain-text body content; ignored when `template` is provided.",
    },
    {
      name: "heading",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Optional bold heading shown above the body content.",
    },
    {
      name: "template",
      kind: "input",
      required: false,
      type: "TemplateRef<unknown> | undefined",
      defaultValue: "undefined",
      description: "Custom body content, rendered instead of `text` when set.",
    },
    {
      name: "position",
      kind: "input",
      required: false,
      type: "TooltipPosition",
      defaultValue: "'right'",
      description: "Side of the anchor element the panel is placed on.",
    },
    {
      name: "left",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "0",
      description: "Absolute `left` pixel coordinate the panel is positioned at, set by `TooltipDirective`.",
    },
    {
      name: "top",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "0",
      description: "Absolute `top` pixel coordinate the panel is positioned at, set by `TooltipDirective`.",
    },
    {
      name: "width",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "231",
      description: "Max width of the panel in pixels.",
    },
    {
      name: "visible",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Shows or hides the panel.",
    },
    {
      name: "tooltipId",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Id applied to the panel element so a trigger can reference it via `aria-describedby`.",
    },
  ],
};
