// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const dataTableApi: ComponentApiDoc = {
  name: "DataTable",
  description: "Sortable, paginated, selectable table driven by a column config. Customize rendering per column with `uiTemplate=\"cell-<key>\"` and `uiTemplate=\"header-<key>\"`, and the empty state with `uiTemplate=\"empty\"`. By default the table runs in client-side mode: pass the full dataset via `data`, and sorting, filtering and paging all happen in memory. Set `totalCount` to switch to controlled mode: pass only the current page's rows in `data`, and the table reflects `page`, `sortState` and `globalFilter` changes instead of slicing or sorting internally, so you can refetch from the backend. Set `rowKey` to extract a stable identity per row, for example `(row) => row.id`, when rows are recreated across page fetches. It defaults to the row object itself.",
  props: [
    {
      name: "data",
      kind: "input",
      required: false,
      type: "readonly T[]",
      defaultValue: "[]",
      description: "Row data. In client-side mode, the full dataset; in controlled mode (`totalCount` set), only the current page's rows.",
    },
    {
      name: "columns",
      kind: "input",
      required: true,
      type: "DataTableColumn<T>[]",
      defaultValue: "",
      description: "Column definitions — header text, sortability, alignment, width, and an optional value accessor.",
    },
    {
      name: "rowKey",
      kind: "input",
      required: false,
      type: "(row: T) => unknown",
      defaultValue: "(row: T) => row",
      description: "Extracts a stable identity per row, used for selection and `@for` tracking. Defaults to the row object itself (reference equality).",
    },
    {
      name: "selectable",
      kind: "input",
      required: false,
      type: "'none' | 'single' | 'multi'",
      defaultValue: "'none'",
      description: "Row selection mode — adds a checkbox column (`multi`) or radio column (`single`) when not `'none'`.",
    },
    {
      name: "selected",
      kind: "model",
      required: false,
      type: "T[]",
      defaultValue: "[]",
      description: "Currently selected rows. Two-way bindable via `[(selected)]`.",
    },
    {
      name: "sortState",
      kind: "model",
      required: false,
      type: "DataTableSort | null",
      defaultValue: "null",
      description: "Active sort column/direction, or `null` when unsorted. Two-way bindable; toggled by clicking a sortable header.",
    },
    {
      name: "page",
      kind: "model",
      required: false,
      type: "number",
      defaultValue: "0",
      description: "Zero-based current page index. Two-way bindable via `[(page)]`.",
    },
    {
      name: "pageSize",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "10",
      description: "Rows per page (client-side mode) — or the row count `data` is expected to contain per page (controlled mode).",
    },
    {
      name: "totalCount",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Switches to controlled mode when provided — see class doc.",
    },
    {
      name: "loading",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Shows skeleton placeholder rows instead of `data` while a fetch is in flight.",
    },
    {
      name: "emptyMessage",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'No data'",
      description: "Fallback text shown when there are no rows to display; overridden by a `uiTemplate=\"empty\"`.",
    },
    {
      name: "globalFilter",
      kind: "model",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Client-side-only free-text filter, matched against every column's rendered value. Two-way bindable.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Accessible name for the underlying `<table>`.",
    },
  ],
};
