// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const drawerApi: ComponentApiDoc = {
  name: "Drawer",
  description: "Slide-in panel overlay opened from the left or right edge, with an optional backdrop. Supports named `header`, `content` and `footer` templates via `uiTemplate`; content is projected directly when no `content` template is given. Behaves like a modal dialog: it renders with `role=\"dialog\"`, closes on Escape, traps Tab focus inside the panel while open, and moves focus into the panel when it opens. Use `Sidebar` instead for a persistent, always-visible navigation layout.",
  props: [
    {
      name: "open",
      kind: "model",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Open/closed state. Two-way bindable via `[(open)]`.",
    },
    {
      name: "side",
      kind: "input",
      required: false,
      type: "DrawerSide",
      defaultValue: "'right'",
      description: "Edge the panel slides in from.",
    },
    {
      name: "backdrop",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "true",
      description: "Whether a dimming backdrop renders behind the panel while open.",
    },
    {
      name: "closeOnBackdrop",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "true",
      description: "Whether clicking the backdrop closes the panel. Ignored when `backdrop` is `false`.",
    },
    {
      name: "showCloseButton",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "true",
      description: "Whether the built-in close (X) button renders in the panel header.",
    },
    {
      name: "disableAnimations",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Skips the slide/fade transitions — useful for tests or reduced-motion setups.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the panel element.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'Drawer'",
      description: "Accessible name for the panel's `role=\"dialog\"`.",
    },
    {
      name: "closed",
      kind: "output",
      required: false,
      type: "void",
      defaultValue: "",
      description: "Fires once the panel has fully closed (after any close animation completes).",
    },
  ],
};
