// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const selectApi: ComponentApiDoc = {
  name: "Select",
  description: "Single or multi-select with a custom dropdown listbox. Set `multi` to allow selecting more than one option; `value` then holds an array of extracted `optionValue`s instead of the whole option. Options can be plain values or objects; when using objects, set `optionLabel`, `optionValue` and `optionDisabledKey` to the property names to read from each. Use `maxSelectableLimit` to cap how many options can be selected in `multi` mode.",
  props: [
    {
      name: "options",
      kind: "input",
      required: false,
      type: "readonly unknown[]",
      defaultValue: "[]",
      description: "Options rendered in the listbox — plain values, or objects keyed by `optionLabel`/`optionValue`/`optionDisabledKey`.",
    },
    {
      name: "multi",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Enables multi-select: `value` becomes an array of extracted `optionValue`s instead of a single option — see the `value` doc.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Text shown in the trigger when nothing is selected.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static label text; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static helper text below the trigger; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "optionLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'label'",
      description: "Property key read off each option object for its display text.",
    },
    {
      name: "optionValue",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'value'",
      description: "Property key read off each option object for its underlying value (used for `multi` selection and equality checks).",
    },
    {
      name: "optionDisabledKey",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'disabled'",
      description: "Property key read off each option object to determine whether that option is disabled.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the trigger and prevents opening the listbox.",
    },
    {
      name: "maxSelectableLimit",
      kind: "input",
      required: false,
      type: "number | null",
      defaultValue: "null",
      description: "In `multi` mode, caps how many options can be selected at once; further selections are ignored once the limit is reached.",
    },
    {
      name: "showOnTop",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Opens the listbox above the trigger instead of below.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Native `id` for the trigger; auto-generated when omitted.",
    },
    {
      name: "value",
      kind: "model",
      required: false,
      type: "unknown",
      defaultValue: "undefined",
      description: "For `multi`, the value is an array of extracted `optionValue`s. For single-select, it's the whole selected option.",
    },
    {
      name: "selected",
      kind: "output",
      required: false,
      type: "unknown",
      defaultValue: "",
      description: "Emits the newly selected option (single-select) or the updated value array (multi-select) on every selection change.",
    },
  ],
};
