// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const selectApi: ComponentApiDoc = {
  name: "Select",
  description: "Single or multi select with a custom (non-native) dropdown listbox. Two real bugs fixed from the original: (1) the option data passed in was mutated in place to track a `selected` flag on each object — including objects owned by the caller, not copies. Selection is now derived by comparing against `value()`/`value()[]` instead, so option data is never touched. (2) the multi-select option row nested a full interactive checkbox inside a `(click)` row — clicking the checkbox fired both its own `(change)` and the row's `(click)`, toggling the option twice (back to its original state). The checkbox is now a purely visual indicator; only the row's own click/keyboard handler drives selection. The original had no ARIA at all (no listbox/option roles, no keyboard navigation). Added `aria-haspopup`/`aria-expanded` on the trigger, `role=\"listbox\"`/`role=\"option\"` with `aria-selected`, and Up/Down/Home/End/Enter/Escape keyboard support via `aria-activedescendant`. The original also registered a `fade` animation trigger that was never actually bound anywhere in the template — the listbox popped open/closed with no transition at all despite the trigger existing. Now wired onto the listbox's `@if` block.",
  props: [
    {
      name: "options",
      kind: "input",
      required: false,
      type: "readonly unknown[]",
      defaultValue: "[]",
      description: "Options rendered in the listbox — plain values, or objects keyed by `optionLabel`/`optionValue`/`optionDisabledKey`.",
    },
    {
      name: "multi",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Enables multi-select: `value` becomes an array of extracted `optionValue`s instead of a single option — see the `value` doc.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Text shown in the trigger when nothing is selected.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static label text; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static helper text below the trigger; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "optionLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'label'",
      description: "Property key read off each option object for its display text.",
    },
    {
      name: "optionValue",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'value'",
      description: "Property key read off each option object for its underlying value (used for `multi` selection and equality checks).",
    },
    {
      name: "optionDisabledKey",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'disabled'",
      description: "Property key read off each option object to determine whether that option is disabled.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the trigger and prevents opening the listbox.",
    },
    {
      name: "maxSelectableLimit",
      kind: "input",
      required: false,
      type: "number | null",
      defaultValue: "null",
      description: "In `multi` mode, caps how many options can be selected at once; further selections are ignored once the limit is reached.",
    },
    {
      name: "showOnTop",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Opens the listbox above the trigger instead of below.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Native `id` for the trigger; auto-generated when omitted.",
    },
    {
      name: "value",
      kind: "model",
      required: false,
      type: "unknown",
      defaultValue: "undefined",
      description: "For `multi()`, the value is an array of extracted `optionValue`s. For single-select, it's the whole selected option (matching the original library's contract).",
    },
    {
      name: "selected",
      kind: "output",
      required: false,
      type: "unknown",
      defaultValue: "",
      description: "Emits the newly selected option (single-select) or the updated value array (multi-select) on every selection change.",
    },
  ],
};
