// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const buttonApi: ComponentApiDoc = {
  name: "Button",
  description: "Button with primary/secondary/tertiary/icon-only variants, loading and inverse states. Colors resolve through the `--color-primary-*` theme tokens (see styles.css) — override those CSS variables to reskin every button at once.",
  props: [
    {
      name: "variant",
      kind: "input",
      required: false,
      type: "ButtonVariant",
      defaultValue: "'primary'",
      description: "Visual style. `'icon'` renders a round icon-only button — pair it with `icon` and `ariaLabel`.",
    },
    {
      name: "attrType",
      kind: "input",
      required: false,
      type: "'button' | 'submit' | 'reset'",
      defaultValue: "'button'",
      description: "Native `type` attribute of the underlying `<button>`.",
    },
    {
      name: "icon",
      kind: "input",
      required: false,
      type: "LucideIconInput | undefined",
      defaultValue: "undefined",
      description: "Icon shown next to the label (or alone, for `variant=\"icon\"`). Accepts a Lucide icon component or icon data.",
    },
    {
      name: "iconPos",
      kind: "input",
      required: false,
      type: "'left' | 'right'",
      defaultValue: "'right'",
      description: "Side the `icon` renders on, relative to the projected label content. Ignored for `variant=\"icon\"`.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the button and applies the disabled visual style.",
    },
    {
      name: "loading",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Shows a spinning loader in place of `icon` and disables the button while `true`.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended after the computed variant/size classes, for one-off overrides.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Required for `variant=\"icon\"` buttons, since they have no visible text label.",
    },
    {
      name: "size",
      kind: "input",
      required: false,
      type: "ButtonSize",
      defaultValue: "'default'",
      description: "Controls height/padding/text size; `'icon'`-variant buttons ignore this and stay a fixed round size.",
    },
    {
      name: "inverse",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Renders the button for use on a dark/colored background (white text/border instead of the tinted default).",
    },
    {
      name: "clicked",
      kind: "output",
      required: false,
      type: "MouseEvent",
      defaultValue: "",
      description: "Fires on a native click (not emitted while `disabled` or `loading`, since the `<button>` itself is disabled then).",
    },
    {
      name: "focused",
      kind: "output",
      required: false,
      type: "FocusEvent",
      defaultValue: "",
      description: "Fires when the button gains focus.",
    },
    {
      name: "blurred",
      kind: "output",
      required: false,
      type: "FocusEvent",
      defaultValue: "",
      description: "Fires when the button loses focus.",
    },
  ],
};
