// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const buttonApi: ComponentApiDoc = {
  name: "Button",
  description: "Button styling and behavior applied directly to a native `<button>` or `<a>`: `<button uiButton>Save</button>`, `<a uiButton routerLink=\"/settings\">Settings</a>`. Because the host is the real element, everything native works as usual: `type`, `[style]`, `class`, `routerLink`, `(click)`, `aria-*`, forms. Put any content inside, including your own icons; `icon` is a shortcut for a Lucide icon next to the label. `variant` sets the style (`primary`, `secondary` outline, `tertiary` text-only, `icon` round icon-only), `color` the severity (`danger`, `success`, `warning`, `info`) or a neutral `surface`, and `shape=\"pill\"` fully rounds a text button. Icon-only buttons need an accessible name: set `aria-label`, or add `uiTooltip` to the same element and its text is used. In development, an icon-only button with neither logs a warning.",
  props: [
    {
      name: "variant",
      kind: "input",
      required: false,
      type: "ButtonVariant",
      defaultValue: "'primary'",
      description: "Visual style. `'icon'` renders a round icon-only button — give it an `aria-label` or a `uiTooltip`.",
    },
    {
      name: "color",
      kind: "input",
      required: false,
      type: "ButtonColor",
      defaultValue: "'primary'",
      description: "Color role: the brand `primary`, a severity (`danger`, `success`, `warning`, `info`), or a neutral `surface`.",
    },
    {
      name: "shape",
      kind: "input",
      required: false,
      type: "ButtonShape",
      defaultValue: "'default'",
      description: "`'pill'` fully rounds a text button. Icon-only buttons are always round.",
    },
    {
      name: "size",
      kind: "input",
      required: false,
      type: "ButtonSize",
      defaultValue: "'default'",
      description: "Controls height/padding/text size; `'icon'`-variant buttons ignore this and stay a fixed round size.",
    },
    {
      name: "icon",
      kind: "input",
      required: false,
      type: "LucideIconInput | undefined",
      defaultValue: "undefined",
      description: "Lucide icon shown next to the label (or alone, for `variant=\"icon\"`). You can also project your own icon markup.",
    },
    {
      name: "iconPos",
      kind: "input",
      required: false,
      type: "'left' | 'right'",
      defaultValue: "'right'",
      description: "Side `icon` renders on, relative to the projected content. Ignored for `variant=\"icon\"`.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the button (on `<a>`: `aria-disabled`, not focusable, not clickable).",
    },
    {
      name: "loading",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Shows a spinning loader in place of the content and disables the button while `true`.",
    },
    {
      name: "inverse",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Renders the button for use on a dark/colored background (white text/border instead of the tinted default).",
    },
    {
      name: "type",
      kind: "input",
      required: false,
      type: "'button' | 'submit' | 'reset'",
      defaultValue: "'button'",
      description: "Native `type` of a `<button>`. Defaults to `'button'` (not the browser's `'submit'`); ignored on `<a>`.",
    },
    {
      name: "aria-label",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Accessible name. For icon-only buttons without it, the text of a `uiTooltip` on the same element is used.",
    },
  ],
};
