// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const legacyButtonApi: ComponentApiDoc = {
  name: "LegacyButton",
  description: "@deprecated Use `<button uiButton>` / `<a uiButton>` (the `Button` component) instead: it styles the native element directly, so `routerLink`, `[style]`, `type`, `aria-*` and projected icons all work. Kept so existing `<ui-button>` templates keep working — import `LegacyButton` in place of `Button` wherever a template still uses `<ui-button>`. Migration: `(clicked)` → `(click)`, `attrType` → `type`, `classNames` → `class`, `ariaLabel` → `aria-label`, `(focused)`/`(blurred)` → `(focus)`/`(blur)`.",
  props: [
    {
      name: "variant",
      kind: "input",
      required: false,
      type: "ButtonVariant",
      defaultValue: "'primary'",
      description: "Visual style. `'icon'` renders a round icon-only button — pair it with `icon` and `ariaLabel`.",
    },
    {
      name: "color",
      kind: "input",
      required: false,
      type: "ButtonColor",
      defaultValue: "'primary'",
      description: "Color role: `primary`, a severity (`danger`, `success`, `warning`, `info`), or a neutral `surface`.",
    },
    {
      name: "shape",
      kind: "input",
      required: false,
      type: "ButtonShape",
      defaultValue: "'default'",
      description: "`'pill'` fully rounds a text button.",
    },
    {
      name: "attrType",
      kind: "input",
      required: false,
      type: "'button' | 'submit' | 'reset'",
      defaultValue: "'button'",
      description: "Native `type` attribute of the underlying `<button>`.",
    },
    {
      name: "icon",
      kind: "input",
      required: false,
      type: "LucideIconInput | undefined",
      defaultValue: "undefined",
      description: "Icon shown next to the label (or alone, for `variant=\"icon\"`).",
    },
    {
      name: "iconPos",
      kind: "input",
      required: false,
      type: "'left' | 'right'",
      defaultValue: "'right'",
      description: "Side of the label the `icon` renders on. Ignored for `variant=\"icon\"`.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the button and applies the disabled visual style.",
    },
    {
      name: "loading",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Shows a spinning loader in place of `icon` and disables the button while `true`.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended after the computed variant/size classes.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Required for `variant=\"icon\"` buttons, since they have no visible text label.",
    },
    {
      name: "size",
      kind: "input",
      required: false,
      type: "ButtonSize",
      defaultValue: "'default'",
      description: "Controls height/padding/text size.",
    },
    {
      name: "inverse",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Renders the button for use on a dark/colored background.",
    },
    {
      name: "clicked",
      kind: "output",
      required: false,
      type: "MouseEvent",
      defaultValue: "",
      description: "Fires on a native click (not while `disabled` or `loading`).",
    },
    {
      name: "focused",
      kind: "output",
      required: false,
      type: "FocusEvent",
      defaultValue: "",
      description: "Fires when the button gains focus.",
    },
    {
      name: "blurred",
      kind: "output",
      required: false,
      type: "FocusEvent",
      defaultValue: "",
      description: "Fires when the button loses focus.",
    },
  ],
};
