export interface NavItem {
  label: string;
  path: string;
}

export const NAV_ITEMS: readonly NavItem[] = [
  { label: 'Accordion', path: 'accordion' },
  { label: 'Alert', path: 'alert' },
  { label: 'Alert Dialog', path: 'alert-dialog' },
  { label: 'Autocomplete', path: 'autocomplete' },
  { label: 'Avatar', path: 'avatar' },
  { label: 'Badge', path: 'badge' },
  { label: 'Breadcrumb', path: 'breadcrumb' },
  { label: 'Button', path: 'button' },
  { label: 'Calendar', path: 'calendar' },
  { label: 'Card', path: 'card' },
  { label: 'Checkbox', path: 'checkbox' },
  { label: 'Combobox', path: 'combobox' },
  { label: 'Command', path: 'command' },
  { label: 'Data Table', path: 'data-table' },
  { label: 'Drawer', path: 'drawer' },
  { label: 'Dropdown Menu', path: 'dropdown-menu' },
  { label: 'File Upload', path: 'file-upload' },
  { label: 'Input', path: 'input' },
  { label: 'Input Group', path: 'input-group' },
  { label: 'Label', path: 'label' },
  { label: 'Link', path: 'link' },
  { label: 'Modal', path: 'modal' },
  { label: 'Notification', path: 'notification' },
  { label: 'Number Input', path: 'number-input' },
  { label: 'Paginator', path: 'paginator' },
  { label: 'Popover', path: 'popover' },
  { label: 'Progress', path: 'progress' },
  { label: 'Questionnaire', path: 'questionnaire' },
  { label: 'Radio', path: 'radio' },
  { label: 'Radio Group', path: 'radio-group' },
  { label: 'Resizable', path: 'resizable' },
  { label: 'Search Input', path: 'search-input' },
  { label: 'Select', path: 'select' },
  { label: 'Separator', path: 'separator' },
  { label: 'Sidebar', path: 'sidebar' },
  { label: 'Skeleton', path: 'skeleton' },
  { label: 'Slider', path: 'slider' },
  { label: 'Spinner', path: 'spinner' },
  { label: 'Stepper', path: 'stepper' },
  { label: 'Table', path: 'table' },
  { label: 'Tabs', path: 'tabs' },
  { label: 'Textarea', path: 'textarea' },
  { label: 'Timeline', path: 'timeline' },
  { label: 'Toast', path: 'toast' },
  { label: 'Toggle', path: 'toggle' },
  { label: 'Tooltip', path: 'tooltip' },
  { label: 'Url Copy', path: 'url-copy' },
];
