// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const calendarApi: ComponentApiDoc = {
  name: "Calendar",
  description: "Month-grid date picker with native forms interop (`ControlValueAccessor`) and a signal-based `[(selected)]` two-way binding for standalone usage — same bridging pattern as `Checkbox`. Fixes carried over from the original: `canSelectCurrentDay` was inverted (it disabled today instead of enabling it) and was redundant with a second, always-on \"no past dates\" check inside `selectDay` that ran regardless of `canSelectPreviousDates` — between the two, today's date could never actually be selected no matter which inputs were set. Both are fixed here: a single `isDayDisabled` check handles today/past/future consistently. The next/previous-month buttons also used to render inconsistently when disabled — the \"prev\" button vanished (`*ngIf`) while \"next\" tried (and failed, via a nonexistent `text-color-icon-disabled` class) to dim; both are now real `disabled` buttons with matching, working styles. The offset math for the first week of the month has been rewritten as a single modulo expression — the original had an unmodded subtraction that went negative for some `startDayOffset` values, worked around with a second special-cased branch elsewhere in the matrix-building loop. The prev/next-month buttons also carried a `fade` trigger binding that was pure dead weight: both buttons are always mounted (never inserted/removed), so the enter/leave transitions it declared could never fire — removed rather than migrated.",
  props: [
    {
      name: "selected",
      kind: "model",
      required: false,
      type: "Date | null",
      defaultValue: "null",
      description: "Currently selected date. Two-way bindable via `[(selected)]`.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the whole calendar — no day, or the prev/next-month buttons, can be interacted with.",
    },
    {
      name: "weekdayNames",
      kind: "input",
      required: false,
      type: "WeekdayNames",
      defaultValue: "DEFAULT_WEEKDAY_NAMES",
      description: "Weekday names, starting from Sunday, rotated for display according to `startDayOffset`.",
    },
    {
      name: "monthNames",
      kind: "input",
      required: false,
      type: "MonthNames",
      defaultValue: "DEFAULT_MONTH_NAMES",
      description: "Month names, January first, used for the header label (e.g. \"March 2026\").",
    },
    {
      name: "startDayOffset",
      kind: "input",
      required: false,
      type: "0 | 1 | 2 | 3 | 4 | 5 | 6",
      defaultValue: "1",
      description: "First day of the week shown in the grid: 0 = Sunday, 1 = Monday, ... 6 = Saturday.",
    },
    {
      name: "disabledDates",
      kind: "input",
      required: false,
      type: "Date[]",
      defaultValue: "[]",
      description: "Specific dates disabled in addition to any weekday/past/future rules.",
    },
    {
      name: "disabledWeekdays",
      kind: "input",
      required: false,
      type: "number[]",
      defaultValue: "[]",
      description: "Weekday indices (0 = Sunday ... 6 = Saturday) disabled on every month, e.g. `[0, 6]`.",
    },
    {
      name: "enabledDates",
      kind: "input",
      required: false,
      type: "Date[] | null",
      defaultValue: "null",
      description: "When set, only dates present in this array are selectable — overrides every other rule.",
    },
    {
      name: "canSelectPreviousDates",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Whether dates before today can be selected.",
    },
    {
      name: "canSelectCurrentDay",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "true",
      description: "Whether today's date can be selected.",
    },
    {
      name: "canDeselectDate",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Whether clicking the already-selected day clears the selection.",
    },
    {
      name: "minEnabledDate",
      kind: "input",
      required: false,
      type: "Date | null",
      defaultValue: "null",
      description: "Earliest month the caller can navigate to; disables the \"previous month\" button once reached.",
    },
    {
      name: "maxEnabledDate",
      kind: "input",
      required: false,
      type: "Date | null",
      defaultValue: "null",
      description: "Latest month the caller can navigate to; disables the \"next month\" button once reached.",
    },
  ],
};
