// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const radioGroupApi: ComponentApiDoc = {
  name: "RadioGroup",
  description: "List or chip picker over an array of options, rendered as its own buttons rather than individual `ui-radio` elements. Single-select by default; set `multiple` for a checkbox-group-style multi-select. Follows the WAI-ARIA pattern for the mode in use: `role=\"radiogroup\"` for single-select, `role=\"group\"` with checkboxes for `multiple`, with roving `tabindex` and arrow-key navigation between options. Use `compareWith` to control how options are matched against the bound value, for example when option objects are reloaded from an API and aren't reference-equal. Set `paginator` to page the rendered options through a built-in paginator instead of rendering them all at once.",
  props: [
    {
      name: "options",
      kind: "input",
      required: false,
      type: "readonly T[]",
      defaultValue: "[]",
      description: "Options rendered as radios/chips, in the given order.",
    },
    {
      name: "type",
      kind: "input",
      required: false,
      type: "'list' | 'chips'",
      defaultValue: "'list'",
      description: "Visual layout — a vertical list of rows, or a wrapping row of pill-shaped chips.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Accessible name for the `radiogroup` element.",
    },
    {
      name: "optionClassNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Overrides the default classes applied to an unselected option.",
    },
    {
      name: "selectedClassNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Overrides the default classes applied to the selected option.",
    },
    {
      name: "containerClassNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Overrides the default layout classes on the options container.",
    },
    {
      name: "disabledPredicate",
      kind: "input",
      required: false,
      type: "(option: T) => boolean",
      defaultValue: "() => false",
      description: "Called with each option to decide whether it's disabled; return `true` to disable it. Defaults to enabling every option.",
    },
    {
      name: "compareWith",
      kind: "input",
      required: false,
      type: "(a: T, b: T) => boolean",
      defaultValue: "(a, b) => a === b",
      description: "Called with `(optionA, optionB)` to decide whether two options are the same selection — override for option objects that aren't reference-equal to the bound value (e.g. reloaded from an API). Defaults to `===`.",
    },
    {
      name: "multiple",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Allows selecting more than one option at once, rendered as a checkbox group instead of a radio group.",
    },
    {
      name: "paginator",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Pages the rendered options through a `ui-paginator` instead of rendering them all at once.",
    },
    {
      name: "pageSize",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "5",
      description: "Number of options shown per page when `paginator` is enabled.",
    },
    {
      name: "selectedItem",
      kind: "output",
      required: false,
      type: "T",
      defaultValue: "",
      description: "Emits the chosen option when the user selects it, via click or arrow-key navigation.",
    },
  ],
};
