// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const searchInputApi: ComponentApiDoc = {
  name: "SearchInput",
  description: "Search box built from `Input`'s own conventions (id-generation counter, label/caption `UiTemplateDirective` slots, the exact same `<input>` border/focus/disabled classes) rather than nesting `Input` as a child component. Nesting would need to reach into `Input`'s internal DOM to place a trailing clear button next to its already-hardcoded left search icon — Angular's view encapsulation doesn't allow that without `::ng-deep`, so this owns its template instead. `role=\"search\"` on the wrapper, a real `<button>` clear (\"x\") that only renders once there's text, and a `search` output debounced (default 300ms, `debounceMs` overridable) via a plain `setTimeout`/`effect()` pair — no rxjs, matching how this batch of components avoids pulling rxjs into anything that doesn't already depend on it. Clearing emits immediately, bypassing the debounce, since it's an explicit user action rather than mid-typing input.",
  props: [
    {
      name: "value",
      kind: "model",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Current text value. Two-way bindable via `[(value)]`; also works with `formControlName`/`ngModel`.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'Search…'",
      description: "Placeholder text shown when empty.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static label text; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static helper text below the input; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables user interaction.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Native `id` for the `<input>`; auto-generated when omitted.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the input wrapper.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'Search'",
      description: "Accessible name for the input, used when there's no visible `label`.",
    },
    {
      name: "debounceMs",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "300",
      description: "Debounce delay (ms) before `search` fires after the value settles.",
    },
    {
      name: "search",
      kind: "output",
      required: false,
      type: "string",
      defaultValue: "",
      description: "Debounced value, `debounceMs` after the user stops typing (fires immediately on clear).",
    },
  ],
};
