// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const searchInputApi: ComponentApiDoc = {
  name: "SearchInput",
  description: "Search box with a leading search icon and a clear button that appears once there's text. `search` emits the current value `debounceMs` after the user stops typing. Clearing emits immediately, bypassing the debounce.",
  props: [
    {
      name: "value",
      kind: "model",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Current text value. Two-way bindable via `[(value)]`; also works with `formControlName`/`ngModel`.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'Search…'",
      description: "Placeholder text shown when empty.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static label text; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Static helper text below the input; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables user interaction.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Native `id` for the `<input>`; auto-generated when omitted.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the input wrapper.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'Search'",
      description: "Accessible name for the input, used when there's no visible `label`.",
    },
    {
      name: "debounceMs",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "300",
      description: "Debounce delay (ms) before `search` fires after the value settles.",
    },
    {
      name: "search",
      kind: "output",
      required: false,
      type: "string",
      defaultValue: "",
      description: "Debounced value, `debounceMs` after the user stops typing (fires immediately on clear).",
    },
  ],
};
