// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const sliderApi: ComponentApiDoc = {
  name: "Slider",
  description: "Single-thumb range slider built on the native `<input type=\"range\">`, with full keyboard (arrow keys, Home/End, Page Up/Down) and touch support. Use `formatValue` to customize the visible value badge and `aria-valuetext` for values that aren't self-explanatory as a raw number, for example a currency or duration formatter.",
  props: [
    {
      name: "value",
      kind: "model",
      required: false,
      type: "number",
      defaultValue: "0",
      description: "Current numeric value. Two-way bindable via `[(value)]`.",
    },
    {
      name: "min",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "0",
      description: "Minimum allowed value.",
    },
    {
      name: "max",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "100",
      description: "Maximum allowed value.",
    },
    {
      name: "step",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "1",
      description: "Increment size for keyboard/drag interactions.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables dragging/keyboard input and dims the track.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Text label rendered above the track; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Helper text rendered below the track; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Overrides the auto-generated `id` used to associate the label and caption with the input.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the root element.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Accessible name for the range input, used only when no visible `label` is set (defaults to `'Slider'`).",
    },
    {
      name: "showValue",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "true",
      description: "Shows the current (formatted) value next to the label.",
    },
    {
      name: "formatValue",
      kind: "input",
      required: false,
      type: "((value: number) => string) | undefined",
      defaultValue: "undefined",
      description: "Formats the value for the visible badge and `aria-valuetext`.",
    },
  ],
};
