// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const sliderApi: ComponentApiDoc = {
  name: "Slider",
  description: "Single-thumb range slider built on the native `<input type=\"range\">` rather than a hand-built div thumb/track pair, so keyboard support (arrow keys, Home/End, Page Up/Down) and touch dragging come for free from the browser. The filled portion of the track is a decorative absolutely-positioned overlay sitting *behind* the (transparent-track) range input — the input itself stays the actual hit target and focusable element throughout. `formatValue` drives both the visible value badge and `aria-valuetext`, for sliders where the raw number alone isn't self-explanatory (e.g. `(v) => `$${v}`` for a currency slider, or a duration formatter). Follows `Input`'s id-generation (`nextId` counter + `id` override) and label/caption `UiTemplateDirective` slot conventions.",
  props: [
    {
      name: "value",
      kind: "model",
      required: false,
      type: "number",
      defaultValue: "0",
      description: "Current numeric value. Two-way bindable via `[(value)]`.",
    },
    {
      name: "min",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "0",
      description: "Minimum allowed value.",
    },
    {
      name: "max",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "100",
      description: "Maximum allowed value.",
    },
    {
      name: "step",
      kind: "input",
      required: false,
      type: "number",
      defaultValue: "1",
      description: "Increment size for keyboard/drag interactions.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables dragging/keyboard input and dims the track.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Text label rendered above the track; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Helper text rendered below the track; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Overrides the auto-generated `id` used to associate the label and caption with the input.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the root element.",
    },
    {
      name: "ariaLabel",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Accessible name for the range input, used only when no visible `label` is set (defaults to `'Slider'`).",
    },
    {
      name: "showValue",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "true",
      description: "Shows the current (formatted) value next to the label.",
    },
    {
      name: "formatValue",
      kind: "input",
      required: false,
      type: "((value: number) => string) | undefined",
      defaultValue: "undefined",
      description: "Formats the value for the visible badge and `aria-valuetext`.",
    },
  ],
};
