// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const comboboxApi: ComponentApiDoc = {
  name: "Combobox",
  description: "Single-select combobox: a text-input trigger (instead of `Select`'s button trigger) that filters its option list as you type, but still only lets you land on one of the supplied options — free text you don't select from the list is never committed as `value`. For unconstrained free text with suggestions, use `Autocomplete` instead. Positioned with `FloatingPanel` (CDK Overlay) rather than `Select`'s manual absolute positioning. Follows the same `optionLabel`/`optionValue` accessor-function shape as `Select` so option data (plain objects, or primitives) works identically between the two. The displayed input text (\"query\") is a separate signal from the committed `value`: while the panel is open it reflects whatever the user is typing/filtering with; once the panel closes it resyncs to the label of the committed value (or empties out if nothing is selected).",
  props: [
    {
      name: "options",
      kind: "input",
      required: false,
      type: "readonly unknown[]",
      defaultValue: "[]",
      description: "The full list of selectable options, filtered client-side against the typed query while the panel is open.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Placeholder text shown in the trigger input when nothing has been typed or selected.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Label rendered above the trigger input.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Helper text rendered below the trigger input.",
    },
    {
      name: "optionLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'label'",
      description: "Property name read off each option object for its display label, when options are objects rather than primitives.",
    },
    {
      name: "optionValue",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'value'",
      description: "Property name read off each option object for its committed value, when options are objects rather than primitives.",
    },
    {
      name: "optionDisabledKey",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'disabled'",
      description: "Property name read off each option object to determine whether that option is disabled.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the trigger input entirely — it can't be focused or opened.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "DOM id for the trigger input; auto-generated when omitted.",
    },
    {
      name: "value",
      kind: "model",
      required: false,
      type: "unknown",
      defaultValue: "undefined",
      description: "The committed selection — one entry from `options()`, or `undefined`/`null` when empty.",
    },
    {
      name: "selected",
      kind: "output",
      required: false,
      type: "unknown",
      defaultValue: "",
      description: "Fires with the selected option whenever a user picks one from the list.",
    },
  ],
};
