// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const comboboxApi: ComponentApiDoc = {
  name: "Combobox",
  description: "Single-select combobox with a searchable, filterable trigger input, unlike `Select`'s button trigger. Only lets you commit one of the supplied `options` as `value`; typed text that doesn't match an option is never committed. Use `Autocomplete` instead for free text with suggestions. Options can be plain values or objects. When using objects, set `optionLabel`, `optionValue` and `optionDisabledKey` to the property names to read from each option.",
  props: [
    {
      name: "options",
      kind: "input",
      required: false,
      type: "readonly unknown[]",
      defaultValue: "[]",
      description: "The full list of selectable options, filtered client-side against the typed query while the panel is open.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Placeholder text shown in the trigger input when nothing has been typed or selected.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Label rendered above the trigger input.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Helper text rendered below the trigger input.",
    },
    {
      name: "optionLabel",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'label'",
      description: "Property name read off each option object for its display label, when options are objects rather than primitives.",
    },
    {
      name: "optionValue",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'value'",
      description: "Property name read off each option object for its committed value, when options are objects rather than primitives.",
    },
    {
      name: "optionDisabledKey",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "'disabled'",
      description: "Property name read off each option object to determine whether that option is disabled.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the trigger input entirely — it can't be focused or opened.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "DOM id for the trigger input; auto-generated when omitted.",
    },
    {
      name: "value",
      kind: "model",
      required: false,
      type: "unknown",
      defaultValue: "undefined",
      description: "The committed selection — one entry from `options()`, or `undefined`/`null` when empty.",
    },
    {
      name: "selected",
      kind: "output",
      required: false,
      type: "unknown",
      defaultValue: "",
      description: "Fires with the selected option whenever a user picks one from the list.",
    },
  ],
};
