// GENERATED FILE — do not edit by hand. Run `npm run api-docs` to regenerate.
import type { ComponentApiDoc } from '../../docs-ui/api-table/api-table';

export const inputApi: ComponentApiDoc = {
  name: "Input",
  description: "Text input with label and caption slots, a leading or trailing icon, a password visibility toggle, validation states, and an optional inline suggestion dropdown. Set `type=\"password\"` to add a show/hide toggle button, or `type=\"number\"` to restrict typed characters to digits. Use `searchIn` to show a filterable list of suggestions below the field as the user types; navigate it with Arrow Up/Down, Enter and Escape.",
  props: [
    {
      name: "value",
      kind: "model",
      required: false,
      type: "string | number | null",
      defaultValue: "null",
      description: "Current field value. Two-way bindable via `[(value)]`; also wired up for `formControlName`/`ngModel`.",
    },
    {
      name: "type",
      kind: "input",
      required: false,
      type: "InputType",
      defaultValue: "'text'",
      description: "Native `type` — `'password'` adds the show/hide toggle button, `'number'` restricts typed characters to digits.",
    },
    {
      name: "disabled",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Disables the field and its clear/password-toggle buttons.",
    },
    {
      name: "placeholder",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Native placeholder text shown when the field is empty.",
    },
    {
      name: "label",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Label rendered above the field; ignored when a `uiTemplate=\"label\"` is projected.",
    },
    {
      name: "state",
      kind: "input",
      required: false,
      type: "InputState",
      defaultValue: "null",
      description: "Validation state — colors the border/icon and, for `'error'`, sets `aria-invalid`; `null` for the neutral default.",
    },
    {
      name: "icon",
      kind: "input",
      required: false,
      type: "LucideIconInput | undefined",
      defaultValue: "undefined",
      description: "Icon shown inside the field, positioned per `iconPos`.",
    },
    {
      name: "iconPos",
      kind: "input",
      required: false,
      type: "'left' | 'right'",
      defaultValue: "'right'",
      description: "Side the `icon` renders on.",
    },
    {
      name: "id",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "DOM id for the `<input>`; auto-generated when omitted.",
    },
    {
      name: "classNames",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Extra utility classes appended to the field's root element, for one-off overrides.",
    },
    {
      name: "caption",
      kind: "input",
      required: false,
      type: "string",
      defaultValue: "''",
      description: "Helper/error text rendered below the field and linked via `aria-describedby`; ignored when a `uiTemplate=\"caption\"` is projected.",
    },
    {
      name: "searchIn",
      kind: "input",
      required: false,
      type: "string[] | null",
      defaultValue: "null",
      description: "Candidate strings for the inline suggestion dropdown, filtered against the current `value` as the user types. `null` disables suggestions entirely.",
    },
    {
      name: "max",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Native `max` attribute, for `type=\"number\"`.",
    },
    {
      name: "min",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Native `min` attribute, for `type=\"number\"`.",
    },
    {
      name: "maxLength",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Native `maxlength` attribute.",
    },
    {
      name: "minLength",
      kind: "input",
      required: false,
      type: "number | undefined",
      defaultValue: "undefined",
      description: "Native `minlength` attribute.",
    },
    {
      name: "pattern",
      kind: "input",
      required: false,
      type: "string | undefined",
      defaultValue: "undefined",
      description: "Native `pattern` attribute used for HTML5 form validation.",
    },
    {
      name: "required",
      kind: "input",
      required: false,
      type: "boolean",
      defaultValue: "false",
      description: "Marks the field as required for HTML5 form validation.",
    },
    {
      name: "charRegex",
      kind: "input",
      required: false,
      type: "RegExp | undefined",
      defaultValue: "undefined",
      description: "Characters allowed while typing (tested against `KeyboardEvent.key`), not a format validator.",
    },
    {
      name: "focused",
      kind: "output",
      required: false,
      type: "FocusEvent",
      defaultValue: "",
      description: "Fires when the field gains focus.",
    },
    {
      name: "blurred",
      kind: "output",
      required: false,
      type: "FocusEvent",
      defaultValue: "",
      description: "Fires when the field loses focus.",
    },
  ],
};
